trackio:
    write_url: ??
    project: 'ha_schmidhuber'
    run_name: '10k-beta-0.0001'
dataset:
    episodes: 10000
    lancedb_uri: 'db'
    max_episode_steps: 300
    img_size: 64
vae:
    beta: 0.0001
training:
    vae:
        nb_epochs: 1
        lr: 0.001
    rnn:
        nb_epochs: 20
        lr: 0.01
rnn:
    hidden_size: 256
    num_mix: 5
    z_dim: 32
    action_dim: 3
    temp: 0.2
controller:
    nb_rollouts: 100
    state_dim: 32
    hidden_dim: 256
    action_dim: 3
device: 'cpu'
